title: Kenny Huang
author: Kenny Huang
email: kenhuang41@gmail.com
description: Specialist in data analytics and strategy, Princeton Class of 2023
# github_username: kenhuang41

theme: jekyll-theme-cayman
future: true
